Repository DERHAEUPTLING/contao-immobilienscout24-import-bundle, pull requests merged in 2021-09, with the labels that each got.

#32 Fix RegistryInterface problem with doctrine/doctrine-bundle:2.*
  composer.json
  src/Command/ScrapeAttachmentsCommand.php
  src/Repository/AccountRepository.php
  src/Repository/AttachmentRepository.php
  src/Repository/RealEstateRepository.php
  src/Synchronizer/Synchronizer.php
  src/Synchronizer/SynchronizerFactory.php
Labels: bug

#33 Update tools + get ready for PHP8/Sf5/Contao 4.x
  .gitignore
  .php-cs-fixer.php
  composer.json
  src/Annotation/Immoscout24ApiMapperTrait.php
  src/Synchronizer/FileScraper.php
  tests/Command/SyncRealEstateCommandTest.php
Labels: bug, feature

#35 Allow creating access token credentials from within the back end
  composer.json
  src/ContaoManager/Plugin.php
  src/Controller/BackEnd/AccessTokenController.php
  src/Entity/Credentials.php
  src/EventListener/DataContainer/Account.php
  src/OAuth/Server.php
  src/Resources/config/routing.yaml
  src/Resources/config/services.yaml
  src/Resources/contao/dca/tl_immoscout24_account.php
  src/Resources/contao/languages/en/tl_immoscout24_account.php
Labels: feature
